### ISSUE TITLE
Typo server.js or tests/2-functional-tests.js

### ISSUE THREAD

**Issue by IzzieKi** [freeCodeCamp/boilerplate-mochachai#12]
line 19 of server.js should be changed to:
    res.type('txt').send('**H**ello ' + name);

Otherwise, line 57 of tests/2-functional-tests.js should be changed to:
    // It should respond '**h**ello Guest'
or line 59 of tests/2-functional-tests.js to be:
    assert.**notE**qual(res.text, 'hello Guest'');

**Comment by moT01** [comment]
Please open issues on the [main repo](https://github.com/freeCodeCamp/freeCodeCamp/issues) for these. Thanks and happy coding 🎉
